#!/usr/bin/env python3
"""
tools/gen_withdrawn_doc.py

Generate docs/WITHDRAWN.md from iso3166.json.

Usage:
    python3 tools/gen_withdrawn_doc.py
    python3 tools/gen_withdrawn_doc.py --check

--check exits 1 if the committed doc differs from a fresh generation.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


REGISTRY = Path("iso3166.json")
OUTPUT = Path("docs/WITHDRAWN.md")


class FatalError(SystemExit):
    def __init__(self, message: str, code: int = 2) -> None:
        print(f"error: {message}", file=sys.stderr)
        super().__init__(code)


def build(reg: dict) -> str:
    withdrawn = sorted(reg["countries"]["withdrawn"],
                       key=lambda e: e["alpha_2"])
    meta = reg.get("meta", {})
    version = meta.get("version", "?")

    lines: list[str] = []
    lines.append("# Withdrawn ISO 3166 codes")
    lines.append("")
    lines.append(
        "Every entry in the `withdrawn` array of `iso3166.json`, with "
        "its ISO 3166-3 successors. Generated by "
        "`tools/gen_withdrawn_doc.py`. Do not edit by hand."
    )
    lines.append("")
    lines.append(f"Registry version: **{version}**")
    lines.append(f"Entries: **{len(withdrawn)}**")
    lines.append("")
    lines.append("| alpha-2 | alpha-3 | numeric | Name | Withdrawn | Replaced by |")
    lines.append("|---------|---------|---------|------|-----------|-------------|")
    for e in withdrawn:
        succ = ", ".join(e.get("replaced_by") or []) or "—"
        lines.append(
            f"| {e['alpha_2']} | {e['alpha_3']} | {e['numeric']} | "
            f"{e['name']} | {e.get('withdrawal_date') or '—'} | {succ} |"
        )
    lines.append("")

    # Succession chains: withdrawn entries whose replaced_by leads to
    # another withdrawn entry.
    by_a2 = {e["alpha_2"]: e for e in withdrawn}
    chains: list[str] = []
    for e in withdrawn:
        succ = list(e.get("replaced_by") or [])
        chained = [s for s in succ if s in by_a2]
        if chained:
            parts = [f"{e['alpha_2']} ({e['name']}, {e['withdrawal_date']})"]
            for s in chained:
                se = by_a2[s]
                terminal = ", ".join(se.get("replaced_by") or []) or "no further successor"
                parts.append(f"{s} ({se['name']}, {se['withdrawal_date']}) -> {terminal}")
            chains.append("    " + " -> ".join(parts))

    lines.append("## Succession chains")
    lines.append("")
    lines.append(
        "Withdrawn codes whose immediate successors were themselves "
        "withdrawn. A single query should follow the chain to the "
        "terminal successors."
    )
    lines.append("")
    if chains:
        lines.extend(chains)
    else:
        lines.append("    (none)")
    lines.append("")

    lines.append("## The CS case")
    lines.append("")
    lines.append(
        "`CS` was used twice in ISO 3166-3 history: Czechoslovakia "
        "(withdrawn 1993-01-01, replaced by `CZ` and `SK`) and Serbia "
        "and Montenegro (withdrawn 2006-09-26, replaced by `ME` and "
        "`RS`). The registry has one `CS` entry recording the second "
        "use; the first is documented in the entry's `note` field. See "
        "`docs/decisions/withdrawn-codes.md`."
    )
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--registry", type=Path, default=REGISTRY)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    reg = json.loads(args.registry.read_text(encoding="utf-8"))
    text = build(reg)

    if args.check:
        if OUTPUT.exists() and OUTPUT.read_text(encoding="utf-8") == text:
            print(f"{OUTPUT}: OK")
            return 0
        print(f"{OUTPUT}: STALE", file=sys.stderr)
        print("Regenerate with: python3 tools/gen_withdrawn_doc.py",
              file=sys.stderr)
        return 1

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT} ({len(text):,} chars, {text.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except FatalError as exc:
        sys.exit(exc.code)